### ISSUE TITLE
Generated (online) documentation is out of date

### ISSUE THREAD

**Issue by reem** [cgaebel/iobuf#11]
Title says it all.

**Comment by cgaebel** [comment]
http://www.rust-ci.org/cgaebel/iobuf

It looks fine... that's weird. Might you know what the problem is?

**Comment by cgaebel** [comment]
I'm closing this since it seems to be forgotten about. Re-open if you have more info.

**Comment by reem** [comment]
I have no idea what is causing it, but things are at least missing, e.g. AppendBuf.

**Comment by cgaebel** [comment]
Oh god you're right. Even the fonts are different. Not sure what's different here... I'll dig into it.

**Comment by cgaebel** [comment]
Ok I'm hosting them on github pages now. rust-ci is trashcan.
