### ISSUE TITLE
Proposal: Break out Iobuf trait into RIoBuf and WIoBuf

### ISSUE THREAD

**Issue by rrichardson** [cgaebel/iobuf#5]
There are a couple reasons to do this:  
1. The Iobuf trait is very large, and burdensome to impl. 
2. The Iobuf trait requires its implementors to do some dirty things, like unsafe peeking and poking, which then require other traits, which are read only, to make their read operations unsafe. 

If we put all write operations into WIoBuf, it can contain both safe and unsafe write operations, then for things that are guaranteed to be read-only, we can safely provide all common read operations in RIoBuf without being required to to do anything unsafe.  If we still want buffers that can write while being read-only, then they would have to impl both the read and write traits. 

I can implement this and submit a PR if this is a direction you would like to take this. I just want to make sure we're on the same page.

**Comment by rrichardson** [comment]
Now that I think about it, I gues OBuf and RBuf are better names ;)

**Comment by rrichardson** [comment]
I should probably clarify the above, now that I've had coffee.  I would like to implement an Append buf which can write while having atomic readers, which means we have multiple Writable bufs.  I am suggesting that the functionality that is common to the writers be part of its own trait. 

The way that it would look is either  : 
trait Ibuf : Iobuf { ... } 

or trait Ibuf : Show + Clone {}  
and 
trait IoBuf : Iobuf + Ibuf

Since Iobuf is effectively the read-only portion of the trait.

**Comment by rrichardson** [comment]
Also, cloning a writable buffer doesn't make much sense.  So only the implementors of the readable buffers should have to be clonable.

**Comment by cgaebel** [comment]
I think I'm in favor of this idea, especially the abstraction of IBuf and OBuf

**Comment by cgaebel** [comment]
We talked on IRC about this a while ago. Closing this issue as obsolete.
